server:
  port: 10010

spring:
  datasource:
    hsdb: #主数据源
      type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
      driverClass: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
      url: jdbc:mysql://127.0.0.1:3306/hsdb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai # 数据库连接地址
      username: root # 数据库用户名
      #password: X1nUv5*AkE7kE&Qc
      password: 12345678
      filters: stat,wall,mergeStat
      initialSize: 5 #初始化连接数
      maxActive: 10 #最大活动连接数
      maxWait: 20000 #最大等待时间（毫秒）
    slldb: #受患者据源
      type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
      driverClass: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
      url: jdbc:mysql://127.0.0.1:3306/slldb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai # 数据库连接地址
      username: root # 数据库用户名
      #password: X1nUv5*AkE7kE&Qc
      password: 12345678
      filters: stat,wall,mergeStat
      initialSize: 10 #初始化连接数
      maxActive: 50 #最大活动连接数
      maxWait: 20000 #最大等待时间（毫秒）
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 123
    database: 5 #数据库指定索引
    timeout: 10000 #超时时间
    jedis:
      pool:
        max-active: 1000 #连接池最大连接数，负值表示不限制
        max-wait: -1 #连接池最大阻塞等待时间，负值表示不限制
        max-idle: 10 #连接池中最大空闲连接
        min-idle: 2 #连接池中最小空闲连接
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# JWT配置
jwt:
  header: Authorization
  tokenSecret: b9e01a7f087f34d4f02c0a324f06bfb
  #token有效期一天
  expiration: 86400
  tokenPrefix: "Bearer "
  clientTokenHead: "Basic "

